linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    use_key_in_widget_constructors: true
    deprecated_member_use: false
