# Generated by Django 5.2.8 on 2025-11-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('data', models.JSONField()),
                ('synced', models.BooleanField(default=False)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('village', models.CharField(max_length=100)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.relais')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticPaludisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomes', models.JSONField()),
                ('test_type', models.CharField(choices=[('RDT', 'Test rapide'), ('GO', 'Goutte epaisse'), ('NONE', 'Non realise')], default='RDT', max_length=4)),
                ('test_result', models.CharField(blank=True, choices=[('POS', 'Positif'), ('NEG', 'Negatif'), ('IND', 'Indetermine')], max_length=3, null=True)),
                ('classification', models.CharField(choices=[('SIMPLE', 'Paludisme simple'), ('GRAVE', 'Paludisme grave'), ('NON_SUSPECT', 'Non suspect')], max_length=12)),
                ('danger_signs', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField()),
                ('protocol_version', models.CharField(default='v1', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patient')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.relais')),
            ],
        ),
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomes', models.JSONField()),
                ('engine_output', models.JSONField()),
                ('rdt_result', models.CharField(blank=True, choices=[('POS', 'Positif'), ('NEG', 'Negatif'), ('IND', 'Indetermine')], max_length=3, null=True)),
                ('poids_utilise', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('answered', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('final_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.patient')),
                ('relais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.relais')),
            ],
        ),
    ]
