# Generated by Django 5.2.8 on 2025-11-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relais',
            new_name='BaseRelais',
        ),
    ]
